import http from 'node:http';
import { readFile, writeFile, mkdir, stat } from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
const __dirname=path.dirname(fileURLToPath(import.meta.url)),publicDir=path.join(__dirname,'public'),dataDir=path.join(__dirname,'data'),dbFile=path.join(dataDir,'db.json');
const PORT=Number(process.env.PORT||8080),SECRET=process.env.SESSION_SECRET||'teach-me-v8-change-me'; await mkdir(dataDir,{recursive:true});
const id=p=>`${p}_${crypto.randomBytes(6).toString('hex')}`;
function hashPassword(p,s=crypto.randomBytes(16).toString('hex')){return `${s}:${crypto.scryptSync(p,s,64).toString('hex')}`}
function verifyPassword(p,v){try{const[s,h]=v.split(':');return crypto.timingSafeEqual(crypto.scryptSync(p,s,64),Buffer.from(h,'hex'))}catch{return false}}
function tokenFor(u){const payload=Buffer.from(JSON.stringify({id:u.id,role:u.role,exp:Date.now()+43200000})).toString('base64url');return `${payload}.${crypto.createHmac('sha256',SECRET).update(payload).digest('base64url')}`}
function fromToken(t){try{const[p,s]=t.split('.'),e=crypto.createHmac('sha256',SECRET).update(p).digest('base64url');if(!crypto.timingSafeEqual(Buffer.from(s),Buffer.from(e)))return null;const x=JSON.parse(Buffer.from(p,'base64url'));return x.exp>Date.now()?x:null}catch{return null}}
const skills=[{id:'math-fractions',subject:'Mathematics',grade:'Grade 5',domain:'Number & Operations',name:'Add fractions with unlike denominators'},{id:'math-decimals',subject:'Mathematics',grade:'Grade 5',domain:'Number & Operations',name:'Multiply decimals'},{id:'ela-main-idea',subject:'Language Arts',grade:'Grade 5',domain:'Reading',name:'Identify main idea and evidence'},{id:'ela-grammar',subject:'Language Arts',grade:'Grade 5',domain:'Language',name:'Use complete sentences'},{id:'sci-earth',subject:'Science',grade:'Grade 5',domain:'Earth Science',name:'Water cycle and weather'},{id:'sci-life',subject:'Science',grade:'Grade 5',domain:'Life Science',name:'Plant structures and processes'}];
const templates={Mathematics:[['What is 3/4 + 1/8?',['4/12','7/8','1','5/8'],1,'Find a common denominator of 8.'],['Which fraction equals 2/3?',['4/6','3/5','5/8','6/10'],0,'Multiply numerator and denominator by the same number.'],['What is 48 ÷ 6?',['6','7','8','9'],2,'Think: 6 times what equals 48?'],['What is 25% of 80?',['10','20','25','40'],1,'25% is one fourth.'],['A rectangle is 7 cm by 4 cm. What is its area?',['11 cm²','22 cm²','28 cm²','35 cm²'],2,'Area equals length times width.']],Language:[['Which sentence is complete?',['Because it rained.','Running through the park.','The class finished its project.','After school.'],2,'A complete sentence has a subject and predicate.'],['Choose the best synonym for rapid.',['slow','quick','quiet','heavy'],1,'Rapid means fast.'],['Which word is a noun?',['beautiful','jump','teacher','quickly'],2,'A noun names a person, place, thing, or idea.'],['Choose the correct punctuation.',['Where are you going.','Where are you going?','Where are you going!','Where are you going,'],1,'Direct questions end with a question mark.'],['Bees pollinate plants and help many foods grow. What is the main idea?',['Bees sting','Plants are green','Bees help plants reproduce','Food is expensive'],2,'Choose the idea supported by the whole sentence.']],Science:[['Which organ pumps blood?',['Lung','Heart','Kidney','Brain'],1,'Think about the circulatory system.'],['Water changes to vapor through…',['freezing','melting','evaporation','condensation'],2,'Liquid water gains energy and becomes gas.'],['Earth revolves around the…',['Moon','Mars','Sun','Jupiter'],2,'One revolution takes about one year.'],['Plants make food using…',['photosynthesis','digestion','erosion','gravity'],0,'Plants use light energy.'],['Which is a renewable resource?',['Coal','Oil','Sunlight','Natural gas'],2,'Renewable resources replenish naturally.']]};
function makeQuestions(subject,skillId,custom=[]){if(custom.length)return custom.map((q,i)=>({...q,id:q.id||`q${i+1}`}));const src=templates[subject]||templates.Mathematics;return Array.from({length:20},(_,i)=>{const q=src[i%src.length];return{id:`q${i+1}`,skillId,prompt:q[0],options:q[1],correctIndex:q[2],hint:q[3]}})}
const standards=[{id:'CCSS.MATH.5.NF.A.1',subject:'Mathematics',grade:'Grade 5',label:'Add and subtract fractions with unlike denominators'},{id:'CCSS.ELA-LITERACY.RI.5.2',subject:'Language Arts',grade:'Grade 5',label:'Determine main ideas and summarize supporting details'},{id:'NGSS.5-ESS2-1',subject:'Science',grade:'Grade 5',label:'Model interactions among geosphere, hydrosphere, atmosphere, and biosphere'}];
const seed={users:[{id:'u_teacher',name:'Ms. Williams',email:'teacher@teachme.demo',role:'teacher',grade:'Grade 5',passwordHash:hashPassword('TeachMe123!')},{id:'u_student',name:'Maya Johnson',email:'student@teachme.demo',role:'student',grade:'Grade 5',passwordHash:hashPassword('TeachMe123!')},{id:'u_admin',name:'Jordan Lee',email:'admin@teachme.demo',role:'admin',grade:'',passwordHash:hashPassword('TeachMe123!')},{id:'u_parent',name:'Avery Johnson',email:'parent@teachme.demo',role:'parent',grade:'',passwordHash:hashPassword('TeachMe123!')}],schools:[{id:'school_1',name:'Teach Me Academy',plan:'Pilot'}],standards,classes:[{id:'class_1',schoolId:'school_1',name:'Grade 5 Explorers',grade:'Grade 5',teacherId:'u_teacher',code:'TM5A72',studentIds:['u_student']}],skills,questionBank:makeQuestions('Mathematics','math-fractions'),assignments:[{id:'asg_1',classId:'class_1',title:'Fraction Foundations',subject:'Mathematics',skillId:'math-fractions',skill:'Add fractions with unlike denominators',due:'2026-08-10',questionCount:20,secondsPerQuestion:180,status:'assigned',createdBy:'u_teacher',questionIds:makeQuestions('Mathematics','math-fractions').map(q=>q.id)}],attempts:[],drafts:[],messages:[],parentLinks:[{parentId:'u_parent',studentId:'u_student'}],goals:[{id:'goal_1',studentId:'u_student',title:'Complete 3 practice sessions',target:3,progress:0,due:'2026-08-31',createdBy:'u_teacher'}],activityLog:[],lessonPlans:[{id:'lp_1',classId:'class_1',title:'Fractions in Real Life',subject:'Mathematics',objective:'Students will add fractions with unlike denominators using visual models.',date:'2026-08-12',duration:45,materials:'Fraction strips, whiteboard, practice cards',activities:['Warm-up number talk','Teacher modeling','Partner practice','Exit ticket'],createdBy:'u_teacher'}],portfolioItems:[],notifications:[{id:'note_1',userId:'u_parent',title:'Weekly learning update',message:'Maya has a new mathematics assignment due August 10.',read:false,createdAt:new Date().toISOString()}],aiPolicies:{maxDailyMessages:30,gradedWorkMode:'hints_only',teacherVisibility:true,blockedTopics:['personal contact information','unsafe activities']}};
async function loadDb(){try{const d=JSON.parse(await readFile(dbFile,'utf8'));return {...structuredClone(seed),...d,skills:d.skills||skills,questionBank:d.questionBank||seed.questionBank,drafts:d.drafts||[],standards:d.standards||standards,goals:d.goals||[],activityLog:d.activityLog||[],lessonPlans:d.lessonPlans||[],portfolioItems:d.portfolioItems||[],notifications:d.notifications||[],aiPolicies:d.aiPolicies||seed.aiPolicies}}catch{await writeFile(dbFile,JSON.stringify(seed,null,2));return structuredClone(seed)}}
let db=await loadDb(); const save=()=>writeFile(dbFile,JSON.stringify(db,null,2)); const safe=u=>{const{passwordHash,...x}=u;return x};
function json(res,status,data){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify(data))}
async function body(req){let s='';for await(const c of req){s+=c;if(s.length>5e6)throw Error('Payload too large')}return s?JSON.parse(s):{}}
function auth(req){const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return null;const p=fromToken(h.slice(7));return p?db.users.find(u=>u.id===p.id):null}
function need(req,res,roles=[]){const u=auth(req);if(!u){json(res,401,{error:'Authentication required'});return null}if(roles.length&&!roles.includes(u.role)){json(res,403,{error:'Access denied'});return null}return u}
function visible(u){if(u.role==='student'){const classes=db.classes.filter(c=>c.studentIds.includes(u.id));const ids=classes.map(c=>c.id);return{school:db.schools[0],user:safe(u),classes,users:db.users.map(safe),skills:db.skills,standards:db.standards,questionBank:[],assignments:db.assignments.filter(a=>ids.includes(a.classId)),attempts:db.attempts.filter(a=>a.studentId===u.id),drafts:db.drafts.filter(d=>d.studentId===u.id),goals:db.goals.filter(g=>g.studentId===u.id),lessonPlans:[],portfolioItems:db.portfolioItems.filter(p=>p.studentId===u.id),notifications:db.notifications.filter(n=>n.userId===u.id),aiPolicies:db.aiPolicies}}
if(u.role==='parent'){const kids=db.parentLinks.filter(p=>p.parentId===u.id).map(p=>p.studentId);return{school:db.schools[0],user:safe(u),classes:db.classes.filter(c=>c.studentIds.some(s=>kids.includes(s))),users:db.users.map(safe),skills:db.skills,standards:db.standards,questionBank:[],assignments:db.assignments,attempts:db.attempts.filter(a=>kids.includes(a.studentId)),drafts:[],goals:db.goals.filter(g=>kids.includes(g.studentId)),lessonPlans:[],portfolioItems:db.portfolioItems.filter(p=>kids.includes(p.studentId)),notifications:db.notifications.filter(n=>n.userId===u.id),aiPolicies:db.aiPolicies}}
return{school:db.schools[0],user:safe(u),classes:db.classes,users:db.users.map(safe),skills:db.skills,standards:db.standards,questionBank:db.questionBank,assignments:db.assignments,attempts:db.attempts,drafts:db.drafts,goals:db.goals,lessonPlans:db.lessonPlans,portfolioItems:db.portfolioItems,notifications:db.notifications,activityLog:db.activityLog,aiPolicies:db.aiPolicies}}
function assignmentQuestions(a){if(a.customQuestions?.length)return a.customQuestions;let source=(a.questionIds||[]).map(qid=>db.questionBank.find(q=>q.id===qid)).filter(Boolean);if(!source.length)source=makeQuestions(a.subject,a.skillId);return Array.from({length:a.questionCount||20},(_,i)=>({...source[i%source.length],id:`${a.id}_q${i+1}`}))}
async function api(req,res,url){if(req.method==='POST'&&url.pathname==='/api/login'){const x=await body(req),u=db.users.find(v=>v.email.toLowerCase()===String(x.email||'').toLowerCase());if(!u||!verifyPassword(String(x.password||''),u.passwordHash))return json(res,401,{error:'Invalid email or password'});return json(res,200,{token:tokenFor(u),user:safe(u)})}
if(req.method==='GET'&&url.pathname==='/api/dashboard'){const u=need(req,res);if(!u)return;return json(res,200,visible(u))}
if(req.method==='GET'&&url.pathname==='/api/health')return json(res,200,{ok:true,version:'8.0.0',storage:'server-json',cloudReady:true});
if(req.method==='POST'&&url.pathname==='/api/classes'){const u=need(req,res,['teacher','admin']);if(!u)return;const x=await body(req),item={id:id('class'),schoolId:'school_1',name:x.name||'New Class',grade:x.grade||'Grade 5',teacherId:u.id,code:crypto.randomBytes(3).toString('hex').toUpperCase(),studentIds:[]};db.classes.push(item);await save();return json(res,201,item)}
if(req.method==='POST'&&url.pathname==='/api/classes/join'){const u=need(req,res,['student']);if(!u)return;const x=await body(req),c=db.classes.find(v=>v.code===String(x.code||'').toUpperCase());if(!c)return json(res,404,{error:'Class code not found'});if(!c.studentIds.includes(u.id))c.studentIds.push(u.id);await save();return json(res,200,c)}
if(req.method==='POST'&&url.pathname==='/api/goals'){const u=need(req,res,['teacher','admin']);if(!u)return;const x=await body(req),g={id:id('goal'),studentId:x.studentId,title:x.title||'Learning goal',target:Number(x.target||1),progress:0,due:x.due||'',createdBy:u.id};db.goals.push(g);await save();return json(res,201,g)}
if(req.method==='GET'&&url.pathname==='/api/standards'){const u=need(req,res);if(!u)return;return json(res,200,db.standards)}
if(req.method==='POST'&&url.pathname==='/api/portfolio'){const u=need(req,res,['student','teacher','admin']);if(!u)return;const x=await body(req),studentId=u.role==='student'?u.id:x.studentId;if(!studentId)return json(res,400,{error:'Student is required'});const item={id:id('portfolio'),studentId,title:x.title||'Portfolio item',subject:x.subject||'General',type:x.type||'Reflection',description:x.description||'',artifactUrl:x.artifactUrl||'',createdBy:u.id,createdAt:new Date().toISOString()};db.portfolioItems.push(item);await save();return json(res,201,item)}
if(req.method==='POST'&&url.pathname==='/api/lesson-plans'){const u=need(req,res,['teacher','admin']);if(!u)return;const x=await body(req),plan={id:id('lesson'),classId:x.classId,title:x.title||'Lesson Plan',subject:x.subject||'Mathematics',objective:x.objective||'',date:x.date||'',duration:Number(x.duration||45),materials:x.materials||'',activities:Array.isArray(x.activities)?x.activities:[],createdBy:u.id,createdAt:new Date().toISOString()};db.lessonPlans.push(plan);await save();return json(res,201,plan)}
if(req.method==='POST'&&url.pathname==='/api/notifications'){const u=need(req,res,['teacher','admin']);if(!u)return;const x=await body(req),ids=Array.isArray(x.userIds)?x.userIds:[];const created=ids.map(userId=>({id:id('note'),userId,title:x.title||'School update',message:x.message||'',read:false,createdBy:u.id,createdAt:new Date().toISOString()}));db.notifications.push(...created);await save();return json(res,201,created)}
if(req.method==='PATCH'&&url.pathname==='/api/ai-policies'){const u=need(req,res,['admin']);if(!u)return;const x=await body(req);db.aiPolicies={...db.aiPolicies,...x};await save();return json(res,200,db.aiPolicies)}
if(req.method==='GET'&&url.pathname==='/api/reports/weekly'){const u=need(req,res,['teacher','admin','parent']);if(!u)return;let studentIds=u.role==='parent'?db.parentLinks.filter(p=>p.parentId===u.id).map(p=>p.studentId):db.users.filter(x=>x.role==='student').map(x=>x.id);const reports=studentIds.map(studentId=>{const student=db.users.find(x=>x.id===studentId),attempts=db.attempts.filter(a=>a.studentId===studentId&&a.status!=='draft'),avg=attempts.length?Math.round(attempts.reduce((n,a)=>n+(a.teacherScore??a.score),0)/attempts.length/20*100):0;return{student:safe(student),completedSessions:attempts.length,averagePercent:avg,goals:db.goals.filter(g=>g.studentId===studentId),portfolioCount:db.portfolioItems.filter(p=>p.studentId===studentId).length,recommendation:avg<70?'Schedule targeted teacher support and assign a foundational skill.':avg<85?'Continue guided practice and review teacher feedback.':'Offer a challenge skill and celebrate mastery.'}});return json(res,200,{generatedAt:new Date().toISOString(),reports})}
if(req.method==='GET'&&url.pathname==='/api/analytics/class'){const u=need(req,res,['teacher','admin']);if(!u)return;const attempts=db.attempts,graded=attempts.filter(a=>a.status!=='draft'),average=graded.length?graded.reduce((n,a)=>n+(a.teacherScore??a.score),0)/graded.length:0,subjects={};for(const a of graded){const asg=db.assignments.find(v=>v.id===a.assignmentId),s=asg?.subject||'Other';subjects[s]??={total:0,count:0};subjects[s].total+=a.teacherScore??a.score;subjects[s].count++}return json(res,200,{classCount:db.classes.length,studentCount:db.users.filter(x=>x.role==='student').length,assignmentCount:db.assignments.length,completionRate:db.assignments.length?Math.round(graded.length/(db.assignments.length*Math.max(1,db.users.filter(x=>x.role==='student').length))*100):0,averagePercent:Math.round(average/20*100),subjects:Object.fromEntries(Object.entries(subjects).map(([k,v])=>[k,{attempts:v.count,average:Math.round(v.total/v.count/20*100)}])),interventions:db.users.filter(x=>x.role==='student').map(s=>{const a=graded.filter(v=>v.studentId===s.id),avg=a.length?a.reduce((n,v)=>n+(v.teacherScore??v.score),0)/a.length/20*100:null;return avg!==null&&avg<70?{student:s.name,studentId:s.id,reason:`Average mastery is ${Math.round(avg)}%`}:null}).filter(Boolean)})}
if(req.method==='POST'&&url.pathname==='/api/question-bank'){const u=need(req,res,['teacher','admin']);if(!u)return;const x=await body(req);if(!x.prompt||!Array.isArray(x.options)||x.options.length<2)return json(res,400,{error:'Prompt and at least two options are required'});const q={id:id('qb'),subject:x.subject||'Mathematics',grade:x.grade||'Grade 5',skillId:x.skillId||'',standardId:x.standardId||'',difficulty:x.difficulty||'On level',prompt:x.prompt,options:x.options,correctIndex:Number(x.correctIndex||0),hint:x.hint||'',explanation:x.explanation||'',createdBy:u.id};db.questionBank.push(q);await save();return json(res,201,q)}
if(req.method==='GET'&&url.pathname==='/api/question-bank'){const u=need(req,res,['teacher','admin']);if(!u)return;return json(res,200,db.questionBank)}
if(req.method==='POST'&&url.pathname==='/api/assignments'){const u=need(req,res,['teacher','admin']);if(!u)return;const x=await body(req),skill=db.skills.find(s=>s.id===x.skillId);const custom=Array.isArray(x.customQuestions)?x.customQuestions:[];const count=Math.max(1,Math.min(20,Number(x.questionCount||20)));const item={id:id('asg'),classId:x.classId,title:x.title||skill?.name||'New Assignment',subject:x.subject||skill?.subject||'Mathematics',skillId:x.skillId||'',skill:x.skill||skill?.name||'',due:x.due||'',questionCount:count,secondsPerQuestion:Math.max(30,Math.min(600,Number(x.secondsPerQuestion||180))),status:x.publishAt&&new Date(x.publishAt)>new Date()?'scheduled':'assigned',publishAt:x.publishAt||'',createdBy:u.id,customQuestions:custom.slice(0,20),standardId:x.standardId||skill?.standardId||''};db.assignments.push(item);await save();return json(res,201,item)}
const qm=url.pathname.match(/^\/api\/assignments\/([^/]+)\/questions$/);if(req.method==='GET'&&qm){const u=need(req,res,['student']);if(!u)return;const a=db.assignments.find(x=>x.id===qm[1]);if(!a)return json(res,404,{error:'Assignment not found'});const c=db.classes.find(x=>x.id===a.classId);if(!c?.studentIds.includes(u.id))return json(res,403,{error:'Not enrolled'});const qs=assignmentQuestions(a).map(({correctIndex,...q})=>q);const draft=db.drafts.find(d=>d.assignmentId===a.id&&d.studentId===u.id);return json(res,200,{assignment:a,questions:qs,draft:draft||null})}
const dm=url.pathname.match(/^\/api\/assignments\/([^/]+)\/draft$/);if(req.method==='PUT'&&dm){const u=need(req,res,['student']);if(!u)return;const x=await body(req),a=db.assignments.find(v=>v.id===dm[1]);if(!a)return json(res,404,{error:'Assignment not found'});let d=db.drafts.find(v=>v.assignmentId===a.id&&v.studentId===u.id);const data={answers:Array.isArray(x.answers)?x.answers:[],currentIndex:Number(x.currentIndex||0),remaining:Number(x.remaining||a.secondsPerQuestion),updatedAt:new Date().toISOString()};if(d)Object.assign(d,data);else{d={id:id('draft'),assignmentId:a.id,studentId:u.id,...data};db.drafts.push(d)}await save();return json(res,200,d)}
if(req.method==='POST'&&url.pathname==='/api/attempts'){const u=need(req,res,['student']);if(!u)return;const x=await body(req),a=db.assignments.find(v=>v.id===x.assignmentId);if(!a)return json(res,404,{error:'Assignment not found'});const key=assignmentQuestions(a),answers=Array.isArray(x.answers)?x.answers:[],score=answers.reduce((n,v,i)=>n+(v.selectedIndex===key[i]?.correctIndex?1:0),0);const attempt={id:id('att'),assignmentId:a.id,studentId:u.id,answers,score,status:'submitted',submittedAt:new Date().toISOString(),teacherScore:null,feedback:'',rubric:{accuracy:score,reasoning:null,completion:answers.filter(v=>v.selectedIndex!=null).length}};db.attempts.push(attempt);db.activityLog.push({id:id('act'),userId:u.id,type:'assignment_submitted',label:a.title,createdAt:new Date().toISOString()});const goal=db.goals.find(g=>g.studentId===u.id&&g.progress<g.target);if(goal)goal.progress=Math.min(goal.target,goal.progress+1);db.drafts=db.drafts.filter(d=>!(d.assignmentId===a.id&&d.studentId===u.id));await save();return json(res,201,attempt)}
const gm=url.pathname.match(/^\/api\/attempts\/([^/]+)\/grade$/);if(req.method==='PATCH'&&gm){const u=need(req,res,['teacher','admin']);if(!u)return;const x=await body(req),a=db.attempts.find(v=>v.id===gm[1]);if(!a)return json(res,404,{error:'Attempt not found'});a.teacherScore=Math.max(0,Math.min(20,Number(x.teacherScore)));a.feedback=String(x.feedback||'');a.status=x.returnForRevision?'revision_requested':'returned';a.rubric={...a.rubric,...(x.rubric||{})};a.annotations=Array.isArray(x.annotations)?x.annotations:[];a.gradedBy=u.id;a.gradedAt=new Date().toISOString();await save();return json(res,200,a)}
if(req.method==='GET'&&url.pathname==='/api/parent/progress'){const u=need(req,res,['parent']);if(!u)return;const kids=db.parentLinks.filter(p=>p.parentId===u.id).map(p=>p.studentId),students=db.users.filter(s=>kids.includes(s.id)).map(safe),attempts=db.attempts.filter(a=>kids.includes(a.studentId));return json(res,200,{students,attempts,assignments:db.assignments})}
if(req.method==='POST'&&url.pathname==='/api/ai'){const u=need(req,res,['student','teacher']);if(!u)return;const x=await body(req),text=String(x.message||''),today=new Date().toISOString().slice(0,10),used=db.messages.filter(m=>m.userId===u.id&&String(m.createdAt||'').startsWith(today)).length;if(used>=Number(db.aiPolicies.maxDailyMessages||30))return json(res,429,{error:'Daily AI tutoring limit reached'});const grade=x.grade||u.grade||'the student grade';let response=db.aiPolicies.gradedWorkMode==='hints_only'&&/answer|solve it for me/i.test(text)?'I can help with a hint and the next step, but I will not complete graded work for you. Tell me what you have tried so far.':/fraction/i.test(text)?`For ${grade}, start by finding a common denominator. Example: 3/4 = 6/8, so 3/4 + 1/8 = 7/8. Now try a similar problem and explain your first step.`:`I will teach this at ${grade} level. First, tell me the exact skill and what part feels confusing. I will use a hint, example, and a check-for-understanding question.`;db.messages.push({id:id('msg'),userId:u.id,message:text,response,createdAt:new Date().toISOString()});db.activityLog.push({id:id('act'),userId:u.id,type:'ai_tutor',label:text.slice(0,80),createdAt:new Date().toISOString()});await save();return json(res,200,{response,mode:process.env.OPENAI_API_KEY?'api-ready':'safe-demo'})}
if(req.method==='POST'&&url.pathname==='/api/reset'){const u=need(req,res,['admin']);if(!u)return;db=structuredClone(seed);await save();return json(res,200,{ok:true})}return json(res,404,{error:'Not found'})}
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json','.svg':'image/svg+xml','.png':'image/png','.webmanifest':'application/manifest+json'};
async function staticFile(req,res,url){let rel=decodeURIComponent(url.pathname==='/'?'/index.html':url.pathname),file=path.join(publicDir,rel);if(!file.startsWith(publicDir))return json(res,403,{error:'Forbidden'});try{if((await stat(file)).isDirectory())file=path.join(file,'index.html');const c=await readFile(file),ext=path.extname(file);res.writeHead(200,{'content-type':mime[ext]||'application/octet-stream','cache-control':ext==='.html'?'no-cache':'public, max-age=3600'});res.end(c)}catch{const c=await readFile(path.join(publicDir,'index.html'));res.writeHead(200,{'content-type':'text/html; charset=utf-8'});res.end(c)}}
const server=http.createServer(async(req,res)=>{const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);try{url.pathname.startsWith('/api/')?await api(req,res,url):await staticFile(req,res,url)}catch(e){console.error(e);json(res,500,{error:'Server error'})}});server.listen(PORT,()=>console.log(`Teach Me V8 running at http://localhost:${PORT}`));
